1. Importação das bibliotecas

In [1]:
##############################################################################
                 # Importação de bibliotecas e frameworks #

# Pandas e Numpy
import pandas as pd                                       # pandas e numpy
import numpy as np                                        # pandas e numpy
import matplotlib.pyplot as plt                           # Visualização (plotly e matplotlib)
import folium
from folium.plugins import HeatMap

2. Lendo o CSV

In [2]:
file_path = 'datatran2024.csv'
df = pd.read_csv(file_path, sep=";")
df

C:\Users\giova\AppData\Local\Temp\ipykernel_14516\3011053825.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, sep=";")

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,571789,01/01/2024,segunda-feira,03:56:00,ES,101,38,CONCEICAO DA BARRA,Ultrapassagem Indevida,Colisão lateral sentido oposto,...,1,1,1,1,3,-1.848.261,-3.992.379,SPRF-ES,DEL04-ES,UOP02-DEL04-ES
1,571804,01/01/2024,segunda-feira,04:50:00,PI,343,185,PIRIPIRI,Manobra de mudança de faixa,Colisão frontal,...,0,1,0,0,2,-429.603.281,-4.176.732.659,SPRF-PI,DEL02-PI,UOP01-DEL02-PI
2,571806,01/01/2024,segunda-feira,04:30:00,BA,116,578,BREJOES,Ingestão de álcool pelo condutor,Colisão frontal,...,0,1,2,0,4,-1.307.158.302,-399.611.107,SPRF-BA,DEL03-BA,UOP02-DEL03-BA
3,571818,01/01/2024,segunda-feira,06:30:00,SE,101,18,MALHADA DOS BOIS,Reação tardia ou ineficiente do condutor,Saída de leito carroçável,...,1,0,2,1,3,-1.035.601.949,-3.690.552.235,SPRF-SE,DEL02-SE,UOP02-DEL02-SE
4,571838,01/01/2024,segunda-feira,05:00:00,MT,364,240,RONDONOPOLIS,Condutor deixou de manter distância do veículo...,Colisão traseira,...,0,2,1,0,3,-1.617.914.141,-5.478.905.337,SPRF-MT,DEL02-MT,UOP01-DEL02-MT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73151,661295,21/12/2024,sábado,07:00:00,PB,230,"135,2",CAMPINA GRANDE,Ausência de reação do condutor,Saída de leito carroçável,...,0,0,0,1,1,-728.210.346,-3.576.839.447,SPRF-PB,DEL02-PB,UOP01-DEL02-PB
73152,661307,01/12/2024,domingo,06:30:00,RJ,393,298,VOLTA REDONDA,Ausência de reação do condutor,Colisão frontal,...,0,0,0,2,2,-2.254.313.289,-4.411.298.586,SPRF-RJ,DEL07-RJ,UOP02-DEL07-RJ
73153,661377,09/07/2024,terça-feira,16:20:00,ES,101,"101,5",SOORETAMA,Desrespeitar a preferência no cruzamento,Colisão transversal,...,0,0,0,3,2,-1.898.833.904,-3.999.933.491,SPRF-ES,DEL04-ES,UOP02-DEL04-ES
73154,661576,17/12/2024,terça-feira,21:35:00,RJ,101,391,RIO DE JANEIRO,Frear bruscamente,Colisão traseira,...,0,1,0,1,2,-22.894.827,-4.368.492,SPRF-RJ,DEL03-RJ,UOP01-DEL03-RJ
73155,661598,27/12/2024,sexta-feira,13:00:00,ES,101,67,SAO MATEUS,Conversão proibida,Colisão transversal,...,2,0,1,3,3,-1.872.054.021,-398.658.931,SPRF-ES,DEL04-ES,UOP02-DEL04-ES

3. Exploração das colunas

In [4]:
df.info()
df_describe = df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73156 entries, 0 to 73155
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      73156 non-null  object
 1   data_inversa            73156 non-null  object
 2   dia_semana              73156 non-null  object
 3   horario                 73156 non-null  object
 4   uf                      73156 non-null  object
 5   br                      73156 non-null  int64
 6   km                      73156 non-null  object
 7   municipio               73156 non-null  object
 8   causa_acidente          73156 non-null  object
 9   tipo_acidente           73156 non-null  object
 10  classificacao_acidente  73155 non-null  object
 11  fase_dia                73156 non-null  object
 12  sentido_via             73156 non-null  object
 13  condicao_metereologica  73156 non-null  object
 14  tipo_pista              73156 non-null  object
 15  tracado_via             73156 non-null  object
 16  uso_solo                73156 non-null  object
 17  pessoas                 73156 non-null  int64
 18  mortos                  73156 non-null  int64
 19  feridos_leves           73156 non-null  int64
 20  feridos_graves          73156 non-null  int64
 21  ilesos                  73156 non-null  int64
 22  ignorados               73156 non-null  int64
 23  feridos                 73156 non-null  int64
 24  veiculos                73156 non-null  int64
 25  latitude                73156 non-null  object
 26  longitude               73156 non-null  object
 27  regional                73153 non-null  object
 28  delegacia               73120 non-null  object
 29  uop                     73044 non-null  object
dtypes: int64(9), object(21)
memory usage: 16.7+ MB

4. Perguntas de negócio

In [ ]:
# Observando a contagem de acidentes por estado em 2024
df['uf'].value_counts().head()

uf
MG    9296
SC    8381
PR    7576
RJ    6389
RS    5206
Name: count, dtype: int64

In [ ]:
# Observando os tipos de acidente que mais ocorreram
df['tipo_acidente'].value_counts().head()

tipo_acidente
Colisão traseira                 13960
Saída de leito carroçável        10827
Colisão transversal               9385
Colisão lateral mesmo sentido     7902
Tombamento                        6442
Name: count, dtype: int64

In [ ]:
# Observando em qual dia e horário mais ocorrem
df['horario'].value_counts().head()
## Adicionar gráfico e horário médio de acidentes (em média, em qual horário ocorrem mais acidentes)

horario
19:00:00    1117
18:00:00    1022
18:30:00     909
17:00:00     856
08:00:00     823
Name: count, dtype: int64

In [ ]:
df['dia_semana'].value_counts().head()

dia_semana
domingo          11741
sábado           11641
sexta-feira      11300
segunda-feira    10208
quinta-feira      9570
Name: count, dtype: int64

In [ ]:
# O clima influencia nos acidentes?
df['condicao_metereologica'].value_counts().head()

condicao_metereologica
Céu Claro         46271
Nublado           11033
Chuva              7420
Sol                3959
Garoa/Chuvisco     2776
Name: count, dtype: int64

## Por que a maioria dos acidentes ocorrem domingo no período das 17h às 19h?
Essa questão está relacionada principalmente em relação aos fatores:
- Falta de fiscalização
- Visibilidade menor
- Falta de atenção.
- Fadiga
Analisando o conjunto de dados, vemos que a maioria ocorrem domingo e sábado, isto é, são finais de semana. Isto pode estar relacionado com o fato de que as pessoas se importam menos com a segurança no trânsito nesses dias (https://www.portaldotransito.com.br/noticias/fiscalizacao-e-legislacao/estatisticas/estudo-mostra-que-mortes-no-transito-acontecem-mais-aos-finais-de-semana/). Além disso, dias de finais de semana possuem menos fiscalização, e são dias que a fadiga dos condutores fica maior.

## Por que os acidentes ocorrem mais em Minas Gerais do que em outros estados? E por que a colisão traseira é a mais comum?
Em relação a ser em Minas Gerais, vários fatores podem contribuir. O estado possui uma das rodovias mais perigosas do país, a BR-381, e isso pode estar relacionado com trechos perigosos e falta de sinalização. Já em relação a colisão traseira, a causa mais provável é a falta de atenção em relação aos condutores. Por conta de muitas vezes termos fluxo intenso de veículos e trechos perigosos, é preciso frear para evitar esse tipo de acidente, além de manter distância do veículo que está na frente.

## Existe relação entre horário e clima com as causas de acidentes?

## Mapa de calor

In [ ]:
def convert_coord(valor):
    valor = str(valor).replace('.', '')
    return float(valor) / 1e5

df['latitude'] = df['latitude'].apply(convert_coord)
df['longitude'] = df['longitude'].apply(convert_coord)
map = folium.Map(location=[df['latitude'].mean(), df['longitude'].mean()], zoom_start=10)
heat_data = df[['latitude', 'longitude']].values.tolist()
HeatMap(heat_data).add_to(map)
map.save("heatmap.html")